# copied from code example published by Google
# https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/cloud-build/.github/workflows/cloud-build.yml

name: Build using Cloud Build

on:
  push:
    branches:
    - develop

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  SERVICE_NAME: load-generator
  TAG: ${{ github.sha }}


jobs:
  setup-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup gcloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.RUN_SA_EMAIL }}
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}

    # Build and push image to Google Container Registry
    - name: Invoke Cloud Build
      run: |-
        echo TAG=$TAG
        gcloud builds submit \
          --tag "gcr.io/$PROJECT_ID/demoapp/$SERVICE_NAME:$TAG"
